spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI:http://localhost:8180/auth/realms/chris02}
#          jwk-set-uri: https://localhost:8543/auth/realms/chris02/protocol/openid-connect/certs
