spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: ${AUTH_ISSUER_URI:https://idcs-ff72d424ef424056bfc689d6a41302cb.identity.oraclecloud.com/}
          jwk-set-uri: https://idcs-ff72d424ef424056bfc689d6a41302cb.identity.oraclecloud.com:443/admin/v1/SigningCert/jwk
springdoc:
  swagger-ui:
    oauth:
      client-id: osscat-api
      client-secret: "BOoybw8Vi>Lwj8]#.q};"
      scopes:
      - openid
        read
        write
        create
      realm: chris02

