server:
  port: 8081
spring:
  mvc:
    servlet:
      path: /api/v1
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:osscat-mem}
    username: ${DATASOURCE_USER:sa}
    password: ${DATASOURCE_PASS:}
  jpa:
    open-in-view: true
    show-sql: ${JPA_SHOW_SQL:false}
    database-platform: ${JPA_PLATFORM:org.hibernate.dialect.H2Dialect}
    generate-ddl: ${JPA_GENERATE_DDL:true}
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
logging:
  level: 
    '[net.chrisgrollier.amsuite.osscat]': ${VERBOSE:WARN}
    '[org.springframework.security]': ${VERBOSE:WARN}

