name: deploy to aks

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ secrets.CLUSTER_NAME }}
        resource-group: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
    - run: |
        kubectl create namespace ${{ secrets.NAMESPACE }} --dry-run -o json | kubectl apply -f -
   
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          deployment.yml
          service.yml
        namespace: ${{ secrets.NAMESPACE }}
